// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckFile(arg1:string):Promise<string>;

export function CheckLibrary():Promise<void>;

export function CheckURL(arg1:string):Promise<string>;

export function EditItem(arg1:string):Promise<void>;

export function ExtractIcon(arg1:string,arg2:string):Promise<string>;

export function ExtractLink(arg1:string):Promise<string>;

export function GetPageData():Promise<main.PageData>;

export function LoadConfig():Promise<string>;

export function LoadLibrary():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function ReadUrlFile(arg1:string):Promise<main.UrlData>;

export function RunExecutable(arg1:string):Promise<void>;

export function SaveIcon(arg1:string,arg2:string):Promise<void>;

export function SaveLibrary(arg1:string):Promise<string>;
