// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFile(arg1) {
  return window['go']['main']['App']['CheckFile'](arg1);
}

export function CheckURL(arg1) {
  return window['go']['main']['App']['CheckURL'](arg1);
}

export function ConfirmFolderRemove(arg1) {
  return window['go']['main']['App']['ConfirmFolderRemove'](arg1);
}

export function EditItem(arg1) {
  return window['go']['main']['App']['EditItem'](arg1);
}

export function EditURLItem(arg1) {
  return window['go']['main']['App']['EditURLItem'](arg1);
}

export function ExtractFavicon(arg1, arg2) {
  return window['go']['main']['App']['ExtractFavicon'](arg1, arg2);
}

export function ExtractIcon(arg1, arg2) {
  return window['go']['main']['App']['ExtractIcon'](arg1, arg2);
}

export function ExtractLink(arg1) {
  return window['go']['main']['App']['ExtractLink'](arg1);
}

export function Focus(arg1) {
  return window['go']['main']['App']['Focus'](arg1);
}

export function GetPageData() {
  return window['go']['main']['App']['GetPageData']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadLibrary() {
  return window['go']['main']['App']['LoadLibrary']();
}

export function OnReload(arg1) {
  return window['go']['main']['App']['OnReload'](arg1);
}

export function OpenDir(arg1) {
  return window['go']['main']['App']['OpenDir'](arg1);
}

export function OpenFile(arg1, arg2) {
  return window['go']['main']['App']['OpenFile'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ReadUrlFile(arg1) {
  return window['go']['main']['App']['ReadUrlFile'](arg1);
}

export function Reload(arg1, arg2) {
  return window['go']['main']['App']['Reload'](arg1, arg2);
}

export function RunExecutable(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunExecutable'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveIcon(arg1, arg2) {
  return window['go']['main']['App']['SaveIcon'](arg1, arg2);
}

export function SaveLibrary(arg1) {
  return window['go']['main']['App']['SaveLibrary'](arg1);
}

export function ShowInExplorer(arg1, arg2) {
  return window['go']['main']['App']['ShowInExplorer'](arg1, arg2);
}

export function ShowSettings() {
  return window['go']['main']['App']['ShowSettings']();
}

export function SystemError(arg1, arg2, arg3) {
  return window['go']['main']['App']['SystemError'](arg1, arg2, arg3);
}
